### ISSUE TITLE
Upload file with Chinese character in the name

### ISSUE THREAD

**Issue by lanlan3322** [kleros/linguo#18] opened 2020-08-06 09:35 UTC
Internal server error.

**Comment by twfhyr** [comment] 2020-08-07 11:03
Let me describe the details. I test Linguo by uploading a file named 测试.txt. After that, when I view the Translated Text on ipfs, it showed 'Internal Server Error'. Below is the link of ipfs:
https://ipfs.kleros.io/ipfs/QmWGac8pNxBhpen5Ef6TSYfcNq2dU714yPB9H9RWcnfJCj/%E6%B5%8B%E8%AF%95.txt


Then I guess this may be caused by the Chinese chracter so I change the file name to testtian7.txt, This time I can browse the text, but it showed some illegal characters. 
https://ipfs.kleros.io/ipfs/QmZ2kmsxeymPs3EteevUYr5w1bGb68LthdZKiaj1p9Zct9/testtian7.txt 

Then I guess maybe because I use Windows notepad default encoding setting(which is ANSE) and it is not compaliable with ipfs. So I change the encoding format to UTF-8. And upload again. This time  everything goes right!
https://ipfs.kleros.io/ipfs/QmNVnyS6C6yPayDDVtqe4hCHsCh45tqaDfXAuuHXjDPmtg/tian7UTF8.txt

From this test, my suggestion is adding a function of preview so that when somebody upload their orginal/translated Text they can confirm everything goes well  just like they expect. Otherwise, it's very easy cause a dispute which maybe because of the platform itself.

**Comment by hbarcelos** [comment] 2020-11-06 01:37
Looks like our IPFS proxy node does not support non-ascii characters.
I'm going to need to hash the filenames so we don't run into this issue anymore.

I will work on that tomorrow.

**Comment by hbarcelos** [comment] 2020-11-06 13:56
The short term solution is to encode non-ASCII file names as a base64 of the first 8 characters of the `sha3` of the file name:
```
测试 -> (sha3) -> 0x92237f84a32f1a873a08b5b5673cca2e102d31c4c6e4e57be7146137ab7263eb
                    \      /
                     \----/  (take first 8 characters of hash for shorter name)
                       ||
                (base64 encode)
                       ||
                       \/
                  OTIyMzdmODQ=

```
In summary:
```
测试.txt -----> OTIyMzdmODQ=.txt
```

Unfortunately if the file name was useful to transmit information, that will be lost.

**Comment by hbarcelos** [comment] 2020-11-06 14:35
@twfhyr I changed the upload list component to display a link to the uploaded file and added a small text to make clear to the user he can visualize it by clicking on the link:

![changes](https://user-images.githubusercontent.com/16565602/98377766-f7e73100-2023-11eb-86dd-e9a6cb3e0c40.png)

The idea is to not clutter the interface, but I'm not sure this message alone will prevent a user in a hurry to submit an invalid file. Any suggestions here?

**Comment by hbarcelos** [comment] 2020-11-06 22:46
It's fixed now!

**Closed by hbarcelos** 2020-11-06 22:46 UTC
